export * from './contact.dto';
export * from './customer-group.dto';
export * from './customer-address.dto';
export * from './credit-limit.dto';
export * from './loyalty.dto';
export * from './opportunity.dto';
export * from './task.dto';
export * from './price-list.dto';
export * from './customer-note.dto';
