export * from './contact.mapper';
export * from './customer-group.mapper';
export * from './customer-address.mapper';
export * from './credit-limit.mapper';
export * from './loyalty.mapper';
export * from './opportunity.mapper';
export * from './task.mapper';
export * from './price-list.mapper';
export * from './customer-note.mapper';
