import { Module } from '@nestjs/common';
import { PrismaModule } from '../../common/prisma';
import { SharedModule } from '../shared/shared.module';
import { EventBusModule } from '../../common/events';
import { CompaniesModule } from '../companies/companies.module';
import {
  CustomerAddressController,
  ContactController,
  CustomerGroupController,
  CreditLimitController,
  LoyaltyController,
  OpportunityController,
  TaskController,
  PriceListController,
  CustomerNoteController,
  CustomerCreditController,
} from './controllers';
import {
  CustomerAddressService,
  ContactService,
  CustomerGroupService,
  CreditLimitService,
  LoyaltyService,
  OpportunityService,
  TaskService,
  PriceListService,
  CustomerNoteService,
  CustomerCreditLedgerService,
} from './services';
import {
  CustomerAddressRepository,
  ContactRepository,
  CustomerGroupRepository,
  CreditLimitRepository,
  LoyaltyRepository,
  OpportunityRepository,
  TaskRepository,
  PriceListRepository,
  CustomerNoteRepository,
  CustomerCreditLedgerRepository,
} from './repositories';
import {
  CustomerAddressMapper,
  ContactMapper,
  CustomerGroupMapper,
  CreditLimitMapper,
  LoyaltyMapper,
  OpportunityMapper,
  TaskMapper,
  PriceListMapper,
  CustomerNoteMapper,
} from './mappers';

@Module({
  imports: [PrismaModule, SharedModule, EventBusModule, CompaniesModule],
  controllers: [
    CustomerAddressController,
    ContactController,
    CustomerGroupController,
    CreditLimitController,
    LoyaltyController,
    OpportunityController,
    TaskController,
    PriceListController,
    CustomerNoteController,
    CustomerCreditController,
  ],
  providers: [
    CustomerAddressService,
    ContactService,
    CustomerGroupService,
    CreditLimitService,
    LoyaltyService,
    OpportunityService,
    TaskService,
    PriceListService,
    CustomerNoteService,
    CustomerCreditLedgerService,
    CustomerCreditLedgerRepository,
    CustomerAddressRepository,
    ContactRepository,
    CustomerGroupRepository,
    CreditLimitRepository,
    LoyaltyRepository,
    OpportunityRepository,
    TaskRepository,
    PriceListRepository,
    CustomerNoteRepository,
    CustomerAddressMapper,
    ContactMapper,
    CustomerGroupMapper,
    CreditLimitMapper,
    LoyaltyMapper,
    OpportunityMapper,
    TaskMapper,
    PriceListMapper,
    CustomerNoteMapper,
  ],
  exports: [
    CustomerAddressService,
    ContactService,
    CustomerGroupService,
    CreditLimitService,
    LoyaltyService,
    CustomerCreditLedgerService,
  ],
})
export class CrmModule {}
