import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:stockflow/features/dashboard/domain/dashboard_models.dart';
import 'package:stockflow/features/reports/data/report_export.dart';

/// Phase 5D-5 — PDF report export localization.
///
/// Guard 1 (EN contract): the exported report keeps its pre-localization
/// copy byte-for-byte (via getters and the null-l10n fallback).
/// Guard 2: RU/KK get natural translations for every PDF copy string.
/// Guard 3: ARB parity — the new keys exist in all three locales with
/// matching key sets and no duplicates.
AppLocalizations en() => lookupAppLocalizations(const Locale('en'));
AppLocalizations ru() => lookupAppLocalizations(const Locale('ru'));
AppLocalizations kk() => lookupAppLocalizations(const Locale('kk'));

DashboardSummary _summary() => const DashboardSummary(
      todaySales: DaySales(revenue: '1200.00', count: 6),
      yesterdaySales: DaySales(revenue: '900.00', count: 5),
      monthSales: DaySales(revenue: '45000.00', count: 210),
      ordersCount: 210,
      grossRevenue: '45000.00',
      grossProfit: '12000.00',
      inventoryValue: '80000.00',
      lowStockProducts: 3,
      outOfStockProducts: 1,
      customerCount: 12,
      supplierCount: 4,
      purchaseTotal: '25000.00',
    );

List<RecentSale> _sales() => const [
      RecentSale(
        id: 's1',
        saleNumber: 'S-0001',
        createdAt: '2026-08-15',
        status: 'COMPLETED',
        total: '250.00',
        paidAmount: '250.00',
      ),
    ];

void main() {
  group('EN byte-for-byte contract — report PDF copy', () {
    test('title, generated, summary, recent sales, footer', () {
      expect(en().reportPdfTitle, 'StockFlow — Business Report');
      expect(en().reportPdfGeneratedAt('2026-08-15 12:00:00.000'),
          'Generated 2026-08-15 12:00:00.000');
      expect(en().reportPdfPerformanceSummary, 'Performance Summary');
      expect(en().recentSales, 'Recent Sales'); // reused, no duplicate key
      expect(en().reportPdfFooter,
          'StockFlow ERP · Generated by the Reports module');
    });

    test('table headers + empty state', () {
      expect(en().reportPdfToday, 'Today');
      expect(en().reportPdfYesterday, 'Yesterday');
      expect(en().reportPdfMonth, 'Month');
      expect(en().reportPdfGrossProfit, 'Gross Profit');
      expect(en().reportPdfInventoryValue, 'Inventory Value');
      expect(en().reportPdfOrders, 'Orders');
      expect(en().reportPdfAvgOrder, 'Avg. Order');
      expect(en().reportPdfNoSalesInPeriod, 'No sales in this period.');
    });
  });

  group('RU / KK translations', () {
    test('RU values are localized, non-empty, and match the template', () {
      expect(ru().reportPdfTitle, 'StockFlow — Бизнес-отчет');
      expect(ru().reportPdfPerformanceSummary, 'Сводка показателей');
      expect(ru().reportPdfFooter,
          'StockFlow ERP · Сформировано модулем отчетов');
      expect(ru().recentSales, 'Последние продажи');
      expect(ru().reportPdfToday, 'Сегодня');
      expect(ru().reportPdfYesterday, 'Вчера');
      expect(ru().reportPdfMonth, 'Месяц');
      expect(ru().reportPdfGrossProfit, 'Валовая прибыль');
      expect(ru().reportPdfInventoryValue, 'Стоимость запасов');
      expect(ru().reportPdfOrders, 'Заказы');
      expect(ru().reportPdfAvgOrder, 'Средний заказ');
      expect(ru().reportPdfNoSalesInPeriod, 'Продаж за этот период нет.');
    });

    test('KK values are localized, non-empty, and match the template', () {
      expect(kk().reportPdfTitle, 'StockFlow — Бизнес-есеп');
      expect(kk().reportPdfPerformanceSummary, 'Көрсеткіштер жиынтығы');
      expect(kk().reportPdfFooter, 'StockFlow ERP · Есептер модулі құрды');
      expect(kk().recentSales, 'Соңғы сатылымдар');
      expect(kk().reportPdfToday, 'Бүгін');
      expect(kk().reportPdfYesterday, 'Кеше');
      expect(kk().reportPdfMonth, 'Ай');
      expect(kk().reportPdfGrossProfit, 'Жалпы пайда');
      expect(kk().reportPdfInventoryValue, 'Қор құны');
      expect(kk().reportPdfOrders, 'Тапсырыстар');
      expect(kk().reportPdfAvgOrder, 'Орташа тапсырыс');
      expect(kk().reportPdfNoSalesInPeriod, 'Бұл кезеңде сатылым жоқ.');
    });

    test('RU/KK never leak the English template in the generated line',
        () {
      // The placeholder must be substituted — no raw "{date}" left behind.
      expect(ru().reportPdfGeneratedAt('15.08.2026'), isNot(contains('{date}')));
      expect(ru().reportPdfGeneratedAt('15.08.2026'), contains('15.08.2026'));
      expect(kk().reportPdfGeneratedAt('15.08.2026'), isNot(contains('{date}')));
      expect(kk().reportPdfGeneratedAt('15.08.2026'), contains('15.08.2026'));
      expect(ru().reportPdfGeneratedAt('x'), isNot(contains('Generated ')));
      expect(kk().reportPdfGeneratedAt('x'), isNot(contains('Generated ')));
    });

    test('placeholder is substituted in all locales (no raw {date})', () {
      // Generated output never leaks the raw placeholder...
      expect(en().reportPdfGeneratedAt('2026-08-15'), isNot(contains('{date}')));
      expect(ru().reportPdfGeneratedAt('15.08.2026'), isNot(contains('{date}')));
      expect(kk().reportPdfGeneratedAt('15.08.2026'), isNot(contains('{date}')));
      // ...and the argument is rendered.
      expect(en().reportPdfGeneratedAt('2026-08-15'), contains('2026-08-15'));
      expect(ru().reportPdfGeneratedAt('15.08.2026'), contains('15.08.2026'));
      expect(kk().reportPdfGeneratedAt('15.08.2026'), contains('15.08.2026'));
    });
  });

  group('buildPdf localization path', () {
    test('null l10n falls back to EN byte-for-byte and still builds',
        () async {
      final bytes = await ReportExport.buildPdf(
        summary: _summary(),
        sales: _sales(),
        generatedAt: DateTime.utc(2026, 8, 15, 12),
      );
      expect(bytes.length, greaterThan(1000));
    });

    test('builds with EN/RU/KK AppLocalizations', () async {
      for (final loc in [en(), ru(), kk()]) {
        final bytes = await ReportExport.buildPdf(
          summary: _summary(),
          sales: _sales(),
          generatedAt: DateTime.utc(2026, 8, 15, 12),
          l10n: loc,
        );
        expect(bytes.length, greaterThan(1000),
            reason: '${loc.localeName} PDF renders non-trivial output');
      }
    });
  });

  group('ARB parity — no duplicate/new-key drift', () {
    Map<String, dynamic> arb(String file) =>
        jsonDecode(File('lib/l10n/$file').readAsStringSync())
            as Map<String, dynamic>;

    test('EN/RU/KK have identical key sets', () {
      final enKeys = arb('app_en.arb').keys.toSet();
      final ruKeys = arb('app_ru.arb').keys.toSet();
      final kkKeys = arb('app_kk.arb').keys.toSet();
      expect(ruKeys.difference(enKeys), isEmpty, reason: 'RU keys missing in EN');
      expect(kkKeys.difference(enKeys), isEmpty, reason: 'KK keys missing in EN');
      expect(enKeys.difference(ruKeys), isEmpty, reason: 'EN keys missing in RU');
      expect(enKeys.difference(kkKeys), isEmpty, reason: 'EN keys missing in KK');
    });

    test('the 5D-5 keys exist in all locales', () {
      for (final file in ['app_en.arb', 'app_ru.arb', 'app_kk.arb']) {
        final d = arb(file);
        for (final key in [
          'reportPdfTitle',
          'reportPdfGeneratedAt',
          'reportPdfPerformanceSummary',
          'reportPdfFooter',
          'reportPdfToday',
          'reportPdfYesterday',
          'reportPdfMonth',
          'reportPdfGrossProfit',
          'reportPdfInventoryValue',
          'reportPdfOrders',
          'reportPdfAvgOrder',
          'reportPdfNoSalesInPeriod',
          'recentSales', // reused — must still exist
        ]) {
          expect(d.containsKey(key), isTrue,
              reason: '$key missing in $file');
        }
      }
    });

    test('new keys are non-empty in every locale', () {
      for (final file in ['app_en.arb', 'app_ru.arb', 'app_kk.arb']) {
        final d = arb(file);
        for (final key in [
          'reportPdfTitle',
          'reportPdfGeneratedAt',
          'reportPdfPerformanceSummary',
          'reportPdfFooter',
          'reportPdfToday',
          'reportPdfYesterday',
          'reportPdfMonth',
          'reportPdfGrossProfit',
          'reportPdfInventoryValue',
          'reportPdfOrders',
          'reportPdfAvgOrder',
          'reportPdfNoSalesInPeriod',
        ]) {
          final v = d[key] as String;
          expect(v.trim(), isNotEmpty, reason: '$key empty in $file');
        }
      }
    });

    test('reportPdfGeneratedAt keeps the {date} placeholder in every ARB', () {
      // The template in the ARB file must declare the placeholder so the
      // generated getter substitutes it.
      for (final file in ['app_en.arb', 'app_ru.arb', 'app_kk.arb']) {
        final v = arb(file)['reportPdfGeneratedAt'] as String;
        expect(v, contains('{date}'), reason: 'placeholder missing in $file');
      }
    });
  });
}
