export * from './contact.repository';
export * from './customer-group.repository';
export * from './customer-address.repository';
export * from './credit-limit.repository';
export * from './loyalty.repository';
export * from './opportunity.repository';
export * from './task.repository';
export * from './price-list.repository';
export * from './customer-note.repository';
